#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '3.2.0.{build}'

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}



##### 重新指定版本号 #####
assembly_info:
  patch: true
  file: sources\CSHive\Properties\AssemblyInfo.cs            #将上面生成的版本号${version}变量替换原来Lib里的版本信息
  assembly_version: '{version}'
  assembly_file_version: '4.5.0.0'
  assembly_informational_version: '{version}-rc1'


#### 编辑平台特性 #####
#platform:
#  - x86
#  - Any CPU
#
configuration:
#  - Debug
  - Release
#
#matrix:
#  fast_finish: true

nuget:
  project_feed: true

build:
  parallel: true                  # enable MSBuild parallel builds
  publish_wap_xcopy: true
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  
  # MSBuild verbosity level :  quiet|minimal|normal|detailed
  verbosity: minimal

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
    
  - path: sources\CSHive\bin\$(configuration)\
    name: Lib

# pushing all *.nupkg files in directory
  - path: out\*.nupkg


#---------------------------------#
#       tests configuration       #
#---------------------------------#
  
#after_test:
#  - ps: .\nuget\libpack.ps1  ###当项目中发现了对应工程文件 *.csproj 的对应的*.nuspec 配置信息会自动生成发行包与调试包(依赖build.publish_nuget的相关参数)，然后在布署中自动发布。

  
#---------------------------------#
#     deployment configuration    #
#---------------------------------#  
  
deploy:

  - provider: NuGet
    api_key:
      secure: /Z553zFSrf/BSO3PX8dmc0XWOLA034CYAOhp8ZubIlpTHGG5h2O25K9STPOf80Aq
    artifact: /.*\.nupkg/
    on:
      #branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only


  # Deploy to GitHub Releases
  #- provider: GitHub
  #  artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
  #  draft: true
  #  prerelease: false
  #  on:
  #    branch: master                # release from master branch only
  #    appveyor_repo_tag: true       # deploy on tag push only  
  
  
# scripts to run before deployment
before_deploy:

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
#deploy: off  
  
  
##-----------------------------------------------------------------------------##
# 注意：
# 1. yml文件中不允许使用Tab制表符空格，切记。
##-----------------------------------------------------------------------------##

  